### ISSUE TITLE
Query by polygon

### ISSUE THREAD

**Issue by peterqliu** [mapbox/vector-tile-query#72]
In addition to point samples, I would like to query for all features of a certain layer, within a given **area**.

**Use cases:**

- estimate population within a certain area, when source data is polygons with density information (actual need I have now). Enormous potential for real estate, zoning, redistricting.

- estimate area of various land classifications within a certain area ([one implementation with ArcGIS](http://www.greenbelt.org/greenbelt-mapper/) )

- total mileage of hiking trails within a certain area, for road maintenance

**Rough workflow:**

- Use [tile-cover](https://github.com/mapbox/tile-cover) to identify tiles encompassing our query polygon.
- Download tiles, and filter for features intersecting with our polygon.
- Union all polygons and linestrings that are contiguous
- Return as geojson.

In cases where the polygon exceeds 70 tiles at z14 (our API limit), we can either:

- throw error, and advise users to split their shape into multiple smaller polygons
- recursively lumping tiles into lower zooms until tiles<70, with an optional `min_zoom` parameter supplied by the user. This trades coarseness for avoiding a hard fail

cc @tmcw @dnomadb @morganherlocker

**Comment by yhahn** [comment]
I think this is probably a use case that won't make much sense for vector tiles.

It will probably be something you could pull together with the dataset API if it had bbox query support + a little turf -- e.g. you'd grab all features within bbox of polygon and then do a turf-within against the resultset.

@peterqliu what are you trying to build/solve atm that requires this?

**Comment by morganherlocker** [comment]
> recursively lumping tiles into lower zooms until tiles<70, with an optional min_zoom parameter supplied by the user. This trades coarseness for avoiding a hard fail

Note that this will throw off many stats operations in unpredictable ways. For example, measuring the length of the road network: The results will get shorter as your zoom goes lower because roads are being dropped and simplified. 

This definitely can be a good strategy to use, but it might be difficult to package this up for broader usecases on the frontend. On the backend, we have [tile-reduce](https://github.com/mapbox/tile-reduce) for performing these sorts of operations, but it is challenging to use for anyone who does not already know about statistics and spatial algorithms. Also, to illustrate the problem above, I always use tile-reduce on a single zoom level at a time, so that the results can be quantified and explained in a more or less predictable way (adding the variability of zoom levels makes things very complex).

Not to dissuade you; I believe devseed has a clientside fork of tile-reduce that does just what you are describing @peterqliu. For most users though, not having a guarantee that their geometry will always be the same will likely be confusing. It does seem like this would be a perfect fit for the dataset api.

**Comment by peterqliu** [comment]
yes, looks like tiling is actually getting in the way of what I want to do. looking into dataset api instead :eyes: thanks for the feedback y'all
